org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Parchmentマッピング(変数名を読みやすくするためのマッピング)
# 最新版は https://parchmentmc.org/docs/getting-started で確認してください
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# --- 環境設定 ---
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.249
loader_version_range=[1,)

# --- Mod情報 ---
mod_id=obsidianequipment
mod_name=Obsidian Equipment
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.r8xyj74j64.obsidianequipment
mod_authors=r8xyj74j64
mod_description=黒曜石のツール・武器・防具を追加するMOD
